version: "3.6"
services:
    present:
        image: node
        volumes:
            - ./:/app
        ports:
            - "8000:8000"
        working_dir: /app
        entrypoint: ["npm"]
        command: ["start"]
    npm:
        image: node
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: ["npm"]
        command: ["--version"]
